# Generated by Django 5.1.1 on 2024-09-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_onetimepassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepassword',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
